---
all:
  children:
    webservers:
      hosts:
        staging-web1.example.com:
        staging-web2.example.com:
    dbservers:
      hosts:
        staging-db1.example.com:
    loadbalancers:
      hosts:
        staging-lb1.example.com:
